version: "3"
services:
  mysql:
    image: mysql-image
    container_name: mysql-db
    #environment:
    #  - pwd=Pwd#$$%
    ports:
      - 3306:3306
    volumes:
      - ./tpch:/tpch_data
  mongodb:
    image: mongodb-image
    #command: python3 app.py
    #depends_on:
    #  - es
    ports:
      - 27017:27017
    volumes:
      - ./tpch:/tpch_data
#volumes:
#    esdata1:
#      driver: local
# https://docker-curriculum.com/#multi-container-environments