version: "3"
services:
  client:
    image: client-image
    hostname: client
    tty: true
    stdin_open: true
    volumes:
      - ${PWD}/tpch:/tpch
      - ${PWD}/platforms/client:/platform:rw
    command: ["/bin/bash"]
  mysql:
    image: mysql-image
    hostname: mysql
    tty: true
    stdin_open: true
    ports:
      - 3306:3306
    volumes:
      - ${PWD}/tpch:/tpch
      - ${PWD}/platforms/mysql:/scripts
  mongodb:
    image: mongodb-image
    hostname: mongodb
    tty: true
    stdin_open: true
    ports:
      - 27017:27017
    volumes:
      - ${PWD}/tpch:/tpch
      - ${PWD}/platforms/mongodb:/scripts
