version: "3"
services:
  client:
    image: client-image
    hostname: client
    tty: true
    stdin_open: true
    volumes:
      - ${PWD}/tpch:/tpch
      - ${PWD}/platforms/client:/platform:rw
      - ${PWD}/dbknitter/grader.py:/grader.py
    command: ["/bin/bash"]
  mysql:
    image: mysql-image
    hostname: mysql
    tty: true
    stdin_open: true
    volumes:
      - ${PWD}/tpch:/tpch
      - ${PWD}/platforms/mysql:/scripts
  mongodb:
    image: mongodb-image
    hostname: mongodb
    tty: true
    stdin_open: true
    volumes:
      - ${PWD}/tpch:/tpch
      - ${PWD}/platforms/mongodb:/scripts
  redis:
    image: redis-image
    hostname: redis
    tty: true
    stdin_open: true
    volumes:
      - ${PWD}/tpch:/tpch
      - ${PWD}/platforms/redis:/scripts
