# Use the official MySQL image as the base
FROM mysql:latest

# Example: Set maintainer label
LABEL maintainer="your-email@example.com"

# Add any other customizations or commands you want, for example:

# Set environment variables (this is just an example, and is redundant as it's set in the base image)
ENV MYSQL_ROOT_PASSWORD=my-secret-pw

# Copy custom configurations or scripts, if any
# COPY ./my_custom.cnf /etc/mysql/conf.d/
# Any additional layers or commands you want to add come here

