# import libraries
from pymongo import MongoClient
import pandas as pd

# connect to MongoDB and obtain collections 
client = MongoClient('mongodb://mongodb:27017/')
db = client.tpch
nation_table = db.nation
supplier_table = db.supplier
orders_table = db.orders
lineitem_table = db.lineitem

# read from MongoDB into pandas dataframe
nation_df = pd.DataFrame(list(nation_table.find()))
supplier_df = pd.DataFrame(list(supplier_table.find()))
orders_df = pd.DataFrame(list(orders_table.find()))
lineitem_df = pd.DataFrame(list(lineitem_table.find()))

# rename _id column generated by MongoDB
for df in [nation_df, supplier_df, orders_df, lineitem_df]:
    df.rename(columns={'_id': 'id'}, inplace=True)

# perform join and filtering operations as per the query
query_result = (supplier_df.merge(lineitem_df, left_on='S_SUPPKEY', right_on='L_SUPPKEY', how='inner')
                            .merge(orders_df, left_on='L_ORDERKEY', right_on='O_ORDERKEY', how='inner')
                            .merge(nation_df, left_on='S_NATIONKEY', right_on='N_NATIONKEY', how='inner'))

query_result = query_result[(query_result['O_ORDERSTATUS'] == 'F') &
                            (query_result['L_RECEIPTDATE'] > query_result['L_COMMITDATE']) &
                            (query_result['N_NAME'] == 'SAUDI ARABIA')]

# perform group by and count operations
query_result = query_result.groupby(['S_NAME']).size().reset_index(name='NUMWAIT')

# sort and save to csv
query_result.sort_values(by=['NUMWAIT', 'S_NAME'], ascending=[False, True], inplace=True)
query_result.to_csv('query_output.csv', index=False)
